"""empty message

Revision ID: b1e90488f1c6
Revises: 6597ecd33220
Create Date: 2024-10-26 20:36:32.486521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1e90488f1c6'
down_revision = '6597ecd33220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.drop_column('bandwidth')
        batch_op.drop_column('model_name')

    with op.batch_alter_table('computers', schema=None) as batch_op:
        batch_op.alter_column('config_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('computers_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computers', schema=None) as batch_op:
        batch_op.create_foreign_key('computers_ibfk_1', 'configurations', ['config_id'], ['config_id'])
        batch_op.alter_column('config_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('bandwidth', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
