"""Initial migration.

Revision ID: f18fae1197bc
Revises: 
Create Date: 2024-10-26 17:36:29.933476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18fae1197bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_points',
    sa.Column('access_point_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('bandwidth', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('access_point_id')
    )
    op.create_table('configurations',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('processor', sa.String(length=100), nullable=False),
    sa.Column('ram', sa.String(length=50), nullable=False),
    sa.Column('hard_drive', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('ip_phones',
    sa.Column('phone_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('line_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('phone_id')
    )
    op.create_table('monitors',
    sa.Column('monitor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('screen_size', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('monitor_id')
    )
    op.create_table('offices',
    sa.Column('office_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('office_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('office_id')
    )
    op.create_table('printers',
    sa.Column('printer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('printer_type', sa.String(length=50), nullable=False),
    sa.Column('print_speed', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('printer_id')
    )
    op.create_table('routers',
    sa.Column('router_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('connection_speed', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('router_id')
    )
    op.create_table('computers',
    sa.Column('computer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('operating_system', sa.String(length=100), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configurations.config_id'], ),
    sa.PrimaryKeyConstraint('computer_id')
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('surname', sa.String(length=45), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.office_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('employee_equipment',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('computer_id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.Column('access_point_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.access_point_id'], ),
    sa.ForeignKeyConstraint(['computer_id'], ['computers.computer_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.monitor_id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.office_id'], ),
    sa.ForeignKeyConstraint(['phone_id'], ['ip_phones.phone_id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.printer_id'], ),
    sa.ForeignKeyConstraint(['router_id'], ['routers.router_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'computer_id', 'monitor_id', 'phone_id', 'office_id', 'printer_id', 'router_id', 'access_point_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_equipment')
    op.drop_table('employees')
    op.drop_table('computers')
    op.drop_table('routers')
    op.drop_table('printers')
    op.drop_table('offices')
    op.drop_table('monitors')
    op.drop_table('ip_phones')
    op.drop_table('configurations')
    op.drop_table('access_points')
    # ### end Alembic commands ###
