name: Deploy to EC2

on:
  push:
    branches: [ "Laba-5" ]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/ubuntu/Laba4"
          overwrite: true

      - name: SSH: install deps, migrate, restart
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd /home/ubuntu/Laba4

            DB_URL=$(sudo awk -F'"' '/Environment="DATABASE_URL=/{print $2}' /etc/systemd/system/laba4.service)
            export DATABASE_URL="$DB_URL"
            export SQLALCHEMY_DATABASE_URI="$DB_URL"
            export FLASK_APP=app:app
            export FLASK_ENV=production

            /home/ubuntu/Laba4/venv/bin/pip install -r app/requirements.txt || true
            /home/ubuntu/Laba4/venv/bin/flask db upgrade || true
            sudo systemctl restart laba4
            sudo systemctl --no-pager -l status laba4
